Test for gmodule inclusion in all cases
On recent glib versions, it seems gmodule needs to be included
separately from glib/gtk, or it leads to compilation errors,
e.g. undefined reference to `g_module_close'

Signed-off-by: Mathieu Denis <mathieu.denis55@gmail.com>
Signed-off by: Yannick Brosseau <yannick.brosseau@gmail.com>
Signed-off-by: Alexandre Montplaisir <alexandre.montplaisir@gmail.com>

Signed-off-by: Yannick Brosseau <yannick.brosseau@gmail.com>